// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0e44JWHkNX3Pp0e1vjeo4AkRZIAZSIHw',
    appId: '1:745510267993:web:3c0f11c1aaabc107eb5548',
    messagingSenderId: '745510267993',
    projectId: 'stormshop',
    authDomain: 'stormshop.firebaseapp.com',
    storageBucket: 'stormshop.firebasestorage.app',
    measurementId: 'G-L40B0L1P3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG-CeoYufKjoxg9_mlxRG5Y81h2rgXlJ0',
    appId: '1:745510267993:android:631308eafac9c167eb5548',
    messagingSenderId: '745510267993',
    projectId: 'stormshop',
    storageBucket: 'stormshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRzbQpmMkfo2OcrzcBRrP62I85QKFD-bw',
    appId: '1:745510267993:ios:b12d6587f02d59b8eb5548',
    messagingSenderId: '745510267993',
    projectId: 'stormshop',
    storageBucket: 'stormshop.firebasestorage.app',
    iosBundleId: 'com.ecommerce.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRzbQpmMkfo2OcrzcBRrP62I85QKFD-bw',
    appId: '1:745510267993:ios:b12d6587f02d59b8eb5548',
    messagingSenderId: '745510267993',
    projectId: 'stormshop',
    storageBucket: 'stormshop.firebasestorage.app',
    iosBundleId: 'com.ecommerce.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0e44JWHkNX3Pp0e1vjeo4AkRZIAZSIHw',
    appId: '1:745510267993:web:63828ad56b70e969eb5548',
    messagingSenderId: '745510267993',
    projectId: 'stormshop',
    authDomain: 'stormshop.firebaseapp.com',
    storageBucket: 'stormshop.firebasestorage.app',
    measurementId: 'G-WECT69LGL9',
  );
}
